[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"

# Netlify Functions
[functions]
  directory = "netlify/functions"

# Essential plugin for Next.js on Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Force apex domain redirect to www
[[redirects]]
  from = "https://elitexteriorsva.com/*"
  to = "https://www.elitexteriorsva.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://elitexteriorsva.com/*"
  to = "https://www.elitexteriorsva.com/:splat"
  status = 301
  force = true

# Security headers for admin routes
[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cache-Control = "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0"


