[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Netlify Functions
[functions]
  directory = "netlify/functions"

# Plugin for form submissions
[[plugins]]
  package = "@netlify/plugin-form-submissions"


# Essential plugin for Next.js on Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Force apex domain redirect to www
[[redirects]]
  from = "https://elitexteriorsva.com/*"
  to = "https://www.elitexteriorsva.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://elitexteriorsva.com/*"
  to = "https://www.elitexteriorsva.com/:splat"
  status = 301
  force = true


