[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  NETLIFY_NEXT_VERIFY_FORMS = "false"

# Netlify Functions
[functions]
  directory = "netlify/functions"

# Essential plugin for Next.js on Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Force apex domain redirect to www
[[redirects]]
  from = "https://elitexteriorsva.com/*"
  to = "https://www.elitexteriorsva.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://elitexteriorsva.com/*"
  to = "https://www.elitexteriorsva.com/:splat"
  status = 301
  force = true


