[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  NETLIFY_NEXT_VERIFY_FORMS = "false"

# Netlify Functions
[functions]
  directory = "netlify/functions"

# Essential plugin for Next.js on Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"

# SEO Headers
[[headers]]
  for = "/*"
  [headers.values]
    # Security Headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    
    # Performance Headers
    Cache-Control = "public, max-age=31536000, immutable"

# Static Assets Headers
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Images Headers
[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# SEO Files Headers
[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    Content-Type = "application/xml"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    Content-Type = "text/plain"

# Force apex domain redirect to www
[[redirects]]
  from = "https://elitexteriorsva.com/*"
  to = "https://www.elitexteriorsva.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://elitexteriorsva.com/*"
  to = "https://www.elitexteriorsva.com/:splat"
  status = 301
  force = true

# Legacy domain redirects (if you had other domains)
[[redirects]]
  from = "https://eliteexteriors.com/*"
  to = "https://www.elitexteriorsva.com/:splat"
  status = 301
  force = true

# Service-specific redirects for SEO
[[redirects]]
  from = "/pressure-washing"
  to = "/services"
  status = 301

[[redirects]]
  from = "/gutter-cleaning"
  to = "/services"
  status = 301

[[redirects]]
  from = "/christmas-lights"
  to = "/services"
  status = 301

[[redirects]]
  from = "/lawn-care"
  to = "/services"
  status = 301


